<a href="https://colab.research.google.com/github/abiddileepjan7-prog/numpy/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np   # numerical python

#array --- collection of data of same data type(homogenious data)

a=np.array([1,2,3,4])
print(a)


[1 2 3 4]


In [ ]:
import numpy as np   # numerical python

#array --- collection of data of same data type(homogenious data)

a=np.array([1,2,3,4,"'abid"])
print(a)


['1' '2' '3' '4' "'abid"]


In [ ]:
# slicing in array

b=np.array([1,2,3,4,5])


#print 1,2
print(b[0:2])

#print 2,1
print(b[-4::-1])

#print 5,4
print(b[-1:-3:-1])

#print 4,5
print(b[3::])

[1 2]
[2 1]
[5 4]
[4 5]


In [ ]:
# dimension

a=np.array([0,1,2,3])

print(a.ndim)  # ndim is used to check the dimension
 # ndim=1 it is vector

b=np.array([[1,2],[2,3],[3,4]])
print(b.ndim)  #ndim=2 so 2-d array
print(b)

print(b.shape)  # to know the shape  or know hoe namy rows,columns   o/p ===(3,2)   rows 2 columns

1
2
[[1 2]
 [2 3]
 [3 4]]
(3, 2)


In [ ]:
# create a 2*2 matrix 2,3,4,5

a=np.array([[2,3],[4,5]])
print(a.shape)
print(a.ndim)
print(a)

(2, 2)
2
[[2 3]
 [4 5]]


In [ ]:
print(a.size)  # to know the total number of elements

4


In [ ]:
# create a 2*3 matrix and print it,size,shape,dimension

m=np.array([[1,2,3],[3,4,5]])
print(m.shape)
print(m.ndim)
print(m.size)

(2, 3)
2
6


In [ ]:
# create a 4*2 matrix

a=np.array([[1,2],[2,3],[3,4],[4,5]])
print(a.ndim)
print(a.shape)
print(a.size)

2
(4, 2)
8


In [ ]:
# create a 4*4 matrix

a=np.array([[1,2,4,3],[7,3,4,5],[5,4,5,6],[4,5,6,7]])
print(a.ndim)
print(a.shape)
print(a.size)
print(a)

2
(4, 4)
16
[[1 2 4 3]
 [7 3 4 5]
 [5 4 5 6]
 [4 5 6 7]]


# **DAY 2**

In [ ]:
import numpy as np
print(a[0])  # to access the first row
print(a[:,0])  # to print the first column
print(a[1,1])  # to access a specific number using row and column
print(a[3,2:])  # to acces a set of adjacent numbers
print(a[2:,2:])  # to acces a sub matrix inside the main matrix
print(a[2,1:3])  # to access a sub martix  (a[start of row:end +1 of row,start of column:end+1 of column])
print(a[1:3,3])
print(a[1:,1:])

[1 2 4 3]
[1 7 5 4]
3
[6 7]
[[5 6]
 [6 7]]
[4 5]
[5 6]
[[3 4 5]
 [4 5 6]
 [5 6 7]]


In [ ]:
# zeo matrix

z=np.zeros([3,3])  # np.zeros is used to print a zero martix  the dimensioon is given  in the brackets
print(z)

q=np.zeros([3,5],dtype=int)  # dtype is used to change the data type
print(q)
print()
print()
w=np.zeros([3,3,3])
print(w)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [ ]:
# one matrix

x=np.ones([3,3],dtype=int)
print(x)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [ ]:
# createe a 2*2 matrix

a=np.array([[1,2],[3,4]])

b=np.array([[3,1],[6,7]])


In [ ]:
#matrix addittion

print(a+b)

[[ 4  3]
 [ 9 11]]


In [ ]:
#matrix substraction

print(a-b)

[[-2  1]
 [-3 -3]]


In [ ]:
# matrix multipliation
print(a*b)  # not correct matrix multiplication
print()
print(a@b)  # @ is used to multiply matrix
print()
print(a.dot(b))  # _.dot(_) is also used to multiply matrix

[[ 3  2]
 [18 28]]

[[15 15]
 [33 31]]

[[15 15]
 [33 31]]


In [ ]:
# matrix division
print(a/b)

[[0.33333333 2.        ]
 [0.5        0.57142857]]


In [ ]:
# full matrix  if all element in the matrix is same it is called full matrix

z=np.full([3,3],5,dtype=int)  # ([dimension],element)
z

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [ ]:
# create a 3*4 matrix with value 9 and data type comple

z=np.full([3,4],9,dtype=complex)
print(z)

[[9.+0.j 9.+0.j 9.+0.j 9.+0.j]
 [9.+0.j 9.+0.j 9.+0.j 9.+0.j]
 [9.+0.j 9.+0.j 9.+0.j 9.+0.j]]


In [ ]:
# identity matrix  matrix with elements

a=np.identity(3,dtype=int)
print(a)

z=np.eye(3) # it is aslo used to print identity matrix
print(z)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# create a 4*4 matrix

y=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(y)

a=y.reshape(8,2)  # reshape is used to change the shape of matrix the number of elements should be same for conversion
# (8,2) menans 8 row 2 column
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]]


In [ ]:
# arange   a particular range of numbers

a=np.arange(1,10,2)  #(start,end+1,step)
print(a)
b=np.arange(1,12)
print(b)

[1 3 5 7 9]
[ 1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
# create a 5*2 matrix using arange

a=np.arange(1,11).reshape(5,2)  # arange for elements and reshape for the  coversion of it  into 5*2 matrix
print(a)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [ ]:
# create a 3*3 matrix with float values
a=np.array([[2.5,3.6,3.5],[1.5,1.1,6.5],[7.1,2.5,7.1]])
print(a)

[[2.5 3.6 3.5]
 [1.5 1.1 6.5]
 [7.1 2.5 7.1]]


In [ ]:
#floor

z=np.floor(a) #floor is used to round to lower value
print(z)

[[2. 3. 3.]
 [1. 1. 6.]
 [7. 2. 7.]]


In [ ]:
# ceil
z=np.ceil(a)
print(z)

[[3. 4. 4.]
 [2. 2. 7.]
 [8. 3. 8.]]


In [ ]:
# round
z=np.round(a) # incase of .5 round toward even number
print(z)

[[2. 4. 4.]
 [2. 1. 6.]
 [7. 2. 7.]]


In [ ]:
a=np.arange(1,10).reshape(3,3)
print(a)

print(a.max()) # to find the max element in the matrix

print(a.max(axis=1))  #  axis is used to fiind the max elemnt in every row
#axis=1 means row    axis=0 means column  in numpy

print(a.min())
print(a.min(axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
9
[3 6 9]
1
[1 4 7]


In [ ]:
print(a.sum())
print()
print(a.sum(axis=1))
print()
print(a.sum(axis=0))
print()
print(np.sqrt(a))
print()
print(np.sin(a))
print()
print(np.cos(a))
print()
print(np.tan(a))

45

[ 6 15 24]

[12 15 18]

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]

[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]
 [ 0.6569866   0.98935825  0.41211849]]

[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]
 [ 0.75390225 -0.14550003 -0.91113026]]

[[ 1.55740772 -2.18503986 -0.14254654]
 [ 1.15782128 -3.38051501 -0.29100619]
 [ 0.87144798 -6.79971146 -0.45231566]]


In [40]:
print(a.flatten())  # to convert a matrix into a flat format or 1d format

[1 2 3 4 5 6 7 8 9]


In [48]:
# sorting

a=np.arange(3,30,3).reshape(3,3)
print(a)
print(np.sort(a,axis=1))
print(np.argsort(a,axis=1)) #shows the index of sorted matrix

[[ 3  6  9]
 [12 15 18]
 [21 24 27]]
[[ 3  6  9]
 [12 15 18]
 [21 24 27]]
[[0 1 2]
 [0 1 2]
 [0 1 2]]
